services:
  backend:
    build: ./tech-int3-server
    container_name: server
    ports:
      - "3001:3001"
    volumes:
      - ./tech-int3-server:/app
      - /app/node_modules
    restart: "always"

  frontend:
    build: ./frontend
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: "always"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
